[package]
name = "tui-snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
rand = "0.8.5"
tui-canvas = { git = "ssh://git@github.com/danielronalds/tui-canvas.git" }
